function [mse,cv,errdata] = get_err_poisson_order_stat(MB)
%-------------------------------------------------------------------------------------------------
% The "new time B" spike times should ideally have an exponential interval 
%  distribution (generated by a homogeneous Poisson process).  This
%  function generates a mean square error statistic based on the mean
%  square deviation of the Nth arrival time (time B) from the expected 
%  arrival time of a homogeneous unit-rate Poisson process.
%
% USAGE:          [mse,cv,errdata] = get_err_poisson_order_stat(MB,tBrange);
% INPUT:          MB            * matrix of time B spike times (each row is a trial)
% OUTPUT:         mse           * mean square deviation from expected arrival times
%                 cv             * coefficient of variation
%                 errdata       * (struct) returns the following diagnostics:
%                                 errvec : difference between actual and expected spike time, each spike
%                                 spikevec: input spike times collapsed and sorted on single axis
%                                 ISI : expected spike times for unit Poisson process
%                                 delta : spacing between expected spike times
%                                 U : intervals after Poisson --> Uniform [0,1] transformation
%                                 U_expected: expected spike time in transformed variable U
%
% Written by Alex Casti, FDU Department of Mathematics
% Last updated 11 September 2015
%-------------------------------------------------------------------------------------------------

% Get a sorted row vector of spike times collapsed onto single axis (no 0's)
spikevec = reshape(MB',1,numel(MB));
spikevec = sort(spikevec(spikevec > 0)); 

% coefficient of variation (should be unity for Poisson process)
ISI = sort(diff(spikevec));    % sorted ISIs (order statistic samples)
errdata.ISI = ISI;             % original set of intervals (sorted)
cv = std(ISI)/mean(ISI);       % coefficient of variation 

% Transform the ISIs to the unit interval (with rate parameter 1)
ISI = ISI/mean(ISI);           % scale intervals to have mean 1 (i.e. rate parameter 1)
%ISI = unique(ISI);             % only use unique ISIs (there may be duplicate spike times)
N = length(ISI);               % total number of intervals
U = 1 - exp(-ISI);             % Poisson to uniform RV transformation (actually the CDF)
delta = 1/N;
U_expected = delta*(1:N);      % expected time of kth time B spike is k/N  for  N-1 samples
errvec = U - U_expected;       % (signed) deviation from expected time for each spike
mse = mean( errvec.^2 );       % mean square error (i.e. related to variance of arrival times)

% More output variables
errdata.delta = delta;
errdata.errvec = errvec;
errdata.spikevec = spikevec;
errdata.U = U;
errdata.U_expected = U_expected;


